CREATE TABLE [dbo].[DeviceProfileTemplate] (
    [Id]                                     INT           IDENTITY (1, 1) NOT NULL,
    [Version]                                INT           CONSTRAINT [DF_DeviceProfile_Version] DEFAULT ((0)) NOT NULL,
    [Name]                                   VARCHAR (50)  NULL,
    [Description]                            VARCHAR (250) NULL,
    [SiteId]                                 INT           NOT NULL,
    [StatusId]                               INT           NOT NULL,
    [CurrencyId]                             INT           NULL,
    [Created]                                DATETIME2 (7) CONSTRAINT [DF_DeviceProfile_Created] DEFAULT (getdate()) NOT NULL,
    [Updated]                                DATETIME2 (7) CONSTRAINT [DF_DeviceProfile_Updated] DEFAULT (getdate()) NOT NULL,
    [IsReusable]                             BIT           NOT NULL,
    [PinRequired]                            BIT           NOT NULL,
    [IsReloadable]                           BIT           NOT NULL,
    [IsRefundable]                           BIT           NOT NULL,
    [ChargeFeeId]                            INT           NULL,
    [CreatedBy]                              INT           NOT NULL,
    [UpdatedBy]                              INT           NOT NULL,
    [ParentId]                               INT           NULL,
    [DeviceNumberGeneratorTemplateId]        INT           NULL,
    [ExternalDeviceNumberGeneratorReference] VARCHAR (50)  NULL,
    [DeviceLotDefaultsId]                    INT           NULL,
    [PinValidationRegularEx]                 VARCHAR (50)  NULL,
    [ExpirationPolicyId]                     INT           NULL,
    [DeviceProfileTemplateTypeId]            INT           NOT NULL,
    [CanUserChangePin]                       BIT           CONSTRAINT [DF_DeviceProfileTemplate_CanUserChangePin] DEFAULT ((0)) NOT NULL,
    [PinNumberRetries]                       INT           NULL,
    [Code]                                   VARCHAR (50)  NULL,
    [DeviceProfileExpirationTypeId]          INT           CONSTRAINT [DF_DeviceProfileTemplate_DeviceProfileExpirationTypeId] DEFAULT ((1)) NOT NULL,
    [ImageUrl]                               VARCHAR (250) NULL,
    [Virtual]                                BIT           DEFAULT ((0)) NULL,
    [IsBonusRedemption]                      BIT           NULL,
    [Config]                                 VARCHAR (MAX) NULL,
    CONSTRAINT [PK_DeviceProfile_1] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_CreatedBy_DeviceProfileTemplate] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[User] ([UserId]),
    CONSTRAINT [FK_Currency_DeviceProfileTemplate] FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[Currency] ([Id]),
    CONSTRAINT [FK_DeviceNumberGeneratorTemplate_DeviceProfileTemplate] FOREIGN KEY ([DeviceNumberGeneratorTemplateId]) REFERENCES [dbo].[DeviceNumberGeneratorTemplate] ([Id]),
    CONSTRAINT [FK_DeviceProfile_DeviceProfileParentId] FOREIGN KEY ([ParentId]) REFERENCES [dbo].[DeviceProfileTemplate] ([Id]),
    CONSTRAINT [FK_DeviceProfileChargeFee_DeviceProfileTemplate] FOREIGN KEY ([ChargeFeeId]) REFERENCES [dbo].[DeviceProfileChargeFee] ([Id]),
    CONSTRAINT [FK_DeviceProfileStatus_DeviceProfileTemplate] FOREIGN KEY ([StatusId]) REFERENCES [dbo].[DeviceProfileTemplateStatus] ([Id]),
    CONSTRAINT [FK_DeviceProfileTemplate_DeviceProfileExpirationType] FOREIGN KEY ([DeviceProfileExpirationTypeId]) REFERENCES [dbo].[DeviceProfileExpirationType] ([Id]),
    CONSTRAINT [FK_DeviceProfileTemplateType_DeviceProfileTemplate] FOREIGN KEY ([DeviceProfileTemplateTypeId]) REFERENCES [dbo].[DeviceProfileTemplateType] ([Id]),
    CONSTRAINT [FK_ExpirationPolicy_DeviceProfileTemplate] FOREIGN KEY ([ExpirationPolicyId]) REFERENCES [dbo].[DeviceExpirationPolicy] ([Id]),
    CONSTRAINT [FK_Site_DeviceProfileTemplate] FOREIGN KEY ([SiteId]) REFERENCES [dbo].[Site] ([SiteId]),
    CONSTRAINT [FK_UpdatedBy_DeviceProfileTemplate] FOREIGN KEY ([UpdatedBy]) REFERENCES [dbo].[User] ([UserId]),
    CONSTRAINT [FK26E8DE9F1A1B0780] FOREIGN KEY ([StatusId]) REFERENCES [dbo].[DeviceProfileTemplateStatus] ([Id]),
    CONSTRAINT [FK26E8DE9F93DD3551] FOREIGN KEY ([ExpirationPolicyId]) REFERENCES [dbo].[DeviceExpirationPolicy] ([Id]),
    CONSTRAINT [FK26E8DE9FE9B562ED] FOREIGN KEY ([DeviceProfileTemplateTypeId]) REFERENCES [dbo].[DeviceProfileTemplateType] ([Id])
);


GO
ALTER TABLE [dbo].[DeviceProfileTemplate] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);

