CREATE TABLE [dbo].[DeviceNumberGeneratorTemplate] (
    [Id]                             INT           IDENTITY (1, 1) NOT NULL,
    [Version]                        INT           CONSTRAINT [DF_DeviceNumberGeneratorTemplate_Version] DEFAULT ((0)) NOT NULL,
    [CreatedBy]                      INT           NOT NULL,
    [CreatedDate]                    DATETIME2 (7) CONSTRAINT [DF_DeviceNumberGeneratorTemplate_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [Prefix]                         VARCHAR (50)  NULL,
    [Suffix]                         VARCHAR (50)  NULL,
    [TotalNumberLength]              DECIMAL (3)   NOT NULL,
    [StatusId]                       INT           NOT NULL,
    [ClientId]                       INT           NOT NULL,
    [TotalNumbersUsed]               DECIMAL (37)  NOT NULL,
    [AvailableNumbersInPool]         DECIMAL (37)  NULL,
    [MinimumThresholdForPool]        DECIMAL (37)  NULL,
    [DefaultNumberOfDevicesToCreate] DECIMAL (37)  NULL,
    [UseExternal]                    BIT           CONSTRAINT [DF_DeviceNumberGeneratorTemplate_External] DEFAULT ((0)) NULL,
    [InitialDeviceNumberStatusId]    INT           NOT NULL,
    [CheckSumAlgorithmId]            INT           NULL,
    [Name]                           VARCHAR (50)  NULL,
    [Description]                    VARCHAR (500) NULL,
    [NumberCreated]                  BIT           NULL,
    [AlphaNumeric]                   BIT           CONSTRAINT [DF_DeviceNumberGeneratorTemplate_AlphaNumeric] DEFAULT ((0)) NULL,
    [RemainingNumbers]               AS            ((power((10.0),[TotalNumberLength])-(1))-[TotalNumbersUsed]),
    CONSTRAINT [PK_DeviceNumberGeneratorTemplate] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK_Client_CheckSumAlgorithm] FOREIGN KEY ([CheckSumAlgorithmId]) REFERENCES [dbo].[CheckSumAlgorithm] ([Id]),
    CONSTRAINT [FK_Client_DeviceNumberGeneratorTemplate] FOREIGN KEY ([ClientId]) REFERENCES [dbo].[Client] ([ClientId]),
    CONSTRAINT [FK_DeviceNumberGeneratorTemplate_DeviceNumberStatus] FOREIGN KEY ([InitialDeviceNumberStatusId]) REFERENCES [dbo].[DeviceNumberStatus] ([Id]),
    CONSTRAINT [FK_DeviceNumberGeneratorTemplateStatus_DeviceNumberGeneratorTemplate] FOREIGN KEY ([StatusId]) REFERENCES [dbo].[DeviceNumberGeneratorTemplateStatus] ([Id]),
    CONSTRAINT [FK_User_DeviceNumberGeneratorTemplate] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[User] ([UserId]),
    CONSTRAINT [uc_DeviceNumberGeneratorTemplate] UNIQUE NONCLUSTERED ([Prefix] ASC, [TotalNumberLength] ASC, [Suffix] ASC)
);

