CREATE TABLE [dbo].[ImportMemberTable] (
    [UniqueId]                          INT           IDENTITY (1, 1) NOT NULL,
    [Clients_Identifier_String]         VARCHAR (100) NULL,
    [Clients_Identifier_Int]            BIGINT        NULL,
    [External_Communications_Reference] VARCHAR (100) NULL,
    [Title]                             VARCHAR (10)  NULL,
    [Salutation]                        VARCHAR (50)  NULL,
    [Email]                             VARCHAR (255) NULL,
    [GivenName]                         VARCHAR (100) NULL,
    [MiddleName]                        VARCHAR (100) NULL,
    [FamilyName]                        VARCHAR (100) NULL,
    [LanguageCode]                      VARCHAR (2)   NULL,
    [SiteRef]                           VARCHAR (25)  NULL,
    [Dob]                               VARCHAR (20)  NULL,
    [Gender]                            VARCHAR (10)  NULL,
    [Add1]                              VARCHAR (255) NULL,
    [Add2]                              VARCHAR (255) NULL,
    [Street]                            VARCHAR (255) NULL,
    [City]                              VARCHAR (255) NULL,
    [County]                            VARCHAR (255) NULL,
    [Zip]                               VARCHAR (255) NULL,
    [Country]                           VARCHAR (255) NULL,
    [Phone_Fixed]                       VARCHAR (50)  NULL,
    [Phone_Mobile]                      VARCHAR (50)  NULL,
    [EmailContact]                      VARCHAR (5)   NULL,
    [PostContact]                       VARCHAR (5)   NULL,
    [SmsContact]                        VARCHAR (5)   NULL,
    [PhoneContact]                      VARCHAR (5)   NULL,
    [CreateDate]                        DATETIME      NULL,
    [LastModified]                      DATETIME      NULL,
    [LastLogin]                         DATETIME      NULL,
    [Signed]                            VARCHAR (5)   NULL,
    [StaffNo]                           VARCHAR (20)  NULL,
    [ImportFileName]                    VARCHAR (200) NULL,
    [Actioned]                          VARCHAR (10)  NULL,
    [ImportDate]                        DATETIME      NULL,
    [UserID]                            INT           NULL,
    [ProcessedDate]                     DATETIME      NULL,
    [RejectReason]                      VARCHAR (100) NULL,
    [ErrorCode]                         VARCHAR (4)   NULL
);

