CREATE TABLE [dbo].[MemberMergeConfig] (
    [MemberMergeConfigId]       INT        IDENTITY (1, 1) NOT NULL,
    [MinPotentialDupLevel]      FLOAT (53) NOT NULL,
    [MinActualDupLevel]         FLOAT (53) NOT NULL,
    [ScoreExactFirstname]       FLOAT (53) NOT NULL,
    [ScorePartialFirstname]     FLOAT (53) NOT NULL,
    [ScoreFirstLetterFirstname] FLOAT (53) NOT NULL,
    [ScoreExactLastname]        FLOAT (53) NOT NULL,
    [ScorePartialLastname]      FLOAT (53) NOT NULL,
    [ScoreDateOfBirth]          FLOAT (53) NOT NULL,
    [ScoreExactHouseNumber]     FLOAT (53) NOT NULL,
    [ScorePartialHouseNumber]   FLOAT (53) NOT NULL,
    [ScoreExactStreet]          FLOAT (53) NOT NULL,
    [ScorePartialStreet]        FLOAT (53) NOT NULL,
    [ScoreExactCity]            FLOAT (53) NOT NULL,
    [ScorePartialCity]          FLOAT (53) NOT NULL,
    [ScoreExactZip]             FLOAT (53) DEFAULT ((0)) NOT NULL,
    [ScorePartialZip]           FLOAT (53) DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([MemberMergeConfigId] ASC),
    CONSTRAINT [CK__MemberMer__MinAc__0B879873] CHECK ([MinActualDupLevel]>=(0) AND [MinActualDupLevel]<=(100)),
    CONSTRAINT [CK__MemberMer__MinPo__0C7BBCAC] CHECK ([MinPotentialDupLevel]>=(0) AND [MinPotentialDupLevel]<=(100)),
    CONSTRAINT [CK__MemberMer__Score__0D6FE0E5] CHECK ([ScoreDateOfBirth]>=(0) AND [ScoreDateOfBirth]<=(100)),
    CONSTRAINT [CK__MemberMer__Score__0E64051E] CHECK ([ScoreExactCity]>=(0) AND [ScoreExactCity]<=(100)),
    CONSTRAINT [CK__MemberMer__Score__0F582957] CHECK ([ScoreExactFirstname]>=(0) AND [ScoreExactFirstname]<=(100)),
    CONSTRAINT [CK__MemberMer__Score__104C4D90] CHECK ([ScoreExactHouseNumber]>=(0) AND [ScoreExactHouseNumber]<=(100)),
    CONSTRAINT [CK__MemberMer__Score__114071C9] CHECK ([ScoreExactLastname]>=(0) AND [ScoreExactLastname]<=(100)),
    CONSTRAINT [CK__MemberMer__Score__12349602] CHECK ([ScoreExactStreet]>=(0) AND [ScoreExactStreet]<=(100)),
    CONSTRAINT [CK__MemberMergeConfi__1328BA3B] CHECK ([ScoreFirstLetterFirstname]>=(0) AND [ScoreFirstLetterFirstname]<=[ScoreExactFirstname]),
    CONSTRAINT [CK__MemberMergeConfi__141CDE74] CHECK ([ScorePartialCity]>=(0) AND [ScorePartialCity]<=[ScoreExactCity]),
    CONSTRAINT [CK__MemberMergeConfi__151102AD] CHECK ([ScorePartialFirstname]>=(0) AND [ScorePartialFirstname]<=[ScoreExactFirstname]),
    CONSTRAINT [CK__MemberMergeConfi__160526E6] CHECK ([ScorePartialHouseNumber]>=(0) AND [ScorePartialHouseNumber]<=[ScoreExactHouseNumber]),
    CONSTRAINT [CK__MemberMergeConfi__16F94B1F] CHECK ([ScorePartialLastname]>=(0) AND [ScorePartialLastname]<=[ScoreExactLastname]),
    CONSTRAINT [CK__MemberMergeConfi__17ED6F58] CHECK ([ScorePartialStreet]>=(0) AND [ScorePartialStreet]<=[ScoreExactStreet])
);

