CREATE TABLE [dbo].[MemberImport] (
    [UniqueId]            INT             IDENTITY (1, 1) NOT NULL,
    [SiteRef]             VARCHAR (30)    NULL,
    [OldMemberId]         VARCHAR (100)   NULL,
    [MemberId]            INT             NULL,
    [DeviceId]            VARCHAR (20)    NULL,
    [AccountId]           INT             NULL,
    [SalutationType]      VARCHAR (50)    NULL,
    [GenderType]          VARCHAR (50)    NULL,
    [TitleType]           VARCHAR (50)    NULL,
    [FirstName]           VARCHAR (100)   NULL,
    [LastName]            VARCHAR (100)   NULL,
    [AddressType]         VARCHAR (30)    NULL,
    [AddressStatus]       VARCHAR (30)    NULL,
    [AddressLine1]        VARCHAR (255)   NULL,
    [AddressLine2]        VARCHAR (255)   NULL,
    [HouseName]           VARCHAR (80)    NULL,
    [HouseNumber]         VARCHAR (50)    NULL,
    [Street]              VARCHAR (255)   NULL,
    [Locality]            VARCHAR (80)    NULL,
    [City]                VARCHAR (255)   NULL,
    [County]              VARCHAR (60)    NULL,
    [Zip]                 VARCHAR (50)    NULL,
    [Country]             VARCHAR (20)    NULL,
    [PostBox]             INT             NULL,
    [PostBoxNumber]       VARCHAR (50)    NULL,
    [DoB]                 VARCHAR (20)    NULL,
    [Email]               VARCHAR (255)   NULL,
    [Phone]               VARCHAR (255)   NULL,
    [Mobile]              VARCHAR (255)   NULL,
    [EmailStatus]         VARCHAR (50)    NULL,
    [UserType]            VARCHAR (80)    NULL,
    [UserSubType]         VARCHAR (80)    NULL,
    [ContactDetailsType]  VARCHAR (80)    NULL,
    [LanguageCode]        VARCHAR (80)    NULL,
    [ContactByEmail]      VARCHAR (4)     NULL,
    [ContactByMail]       VARCHAR (4)     NULL,
    [ContactBySms]        VARCHAR (4)     NULL,
    [ContactByPhone]      VARCHAR (4)     NULL,
    [MonetaryBalance]     DECIMAL (18, 2) NULL,
    [PointsBalance]       DECIMAL (18, 2) NULL,
    [DeviceStatus]        VARCHAR (30)    NULL,
    [Version]             VARCHAR (10)    NULL,
    [TurnoverBalance]     DECIMAL (18, 2) NULL,
    [DeviceType]          VARCHAR (30)    NULL,
    [CommunityId]         VARCHAR (30)    NULL,
    [OldDeviceId]         VARCHAR (50)    NULL,
    [TurnoverBalanceTemp] DECIMAL (18, 2) NULL,
    [MpiId]               VARCHAR (13)    NULL,
    [SocialSecurity]      VARCHAR (50)    NULL,
    [CoverCard]           VARCHAR (20)    NULL,
    [ErrorNotes]          VARCHAR (MAX)   NULL,
    [ErrorCode]           VARCHAR (20)    NULL,
    [ImportTableName]     VARCHAR (200)   NULL,
    [Actioned]            VARCHAR (50)    NULL,
    [ImportDate]          DATETIME        NULL,
    [ProcessedDate]       DATETIME        NULL,
    [Points]              INT             NULL,
    [CardNumber]          VARCHAR (50)    NULL,
    [CardNumberBoss]      VARCHAR (50)    NULL,
    [UserId]              INT             NULL,
    CONSTRAINT [PK_MemberImport_ID] PRIMARY KEY CLUSTERED ([UniqueId] ASC)
);

