CREATE TABLE [dbo].[Promotion] (
    [Id]                              INT            IDENTITY (1, 1) NOT NULL,
    [Version]                         INT            CONSTRAINT [TP__Promotion_Version] DEFAULT ((0)) NOT NULL,
    [Name]                            VARCHAR (100)  NULL,
    [Description]                     VARCHAR (255)  NULL,
    [SiteId]                          INT            NOT NULL,
    [StartDate]                       DATETIME2 (7)  NOT NULL,
    [EndDate]                         DATETIME2 (7)  NULL,
    [StartTime]                       TIME (7)       NULL,
    [EndTime]                         TIME (7)       NULL,
    [Enabled]                         BIT            CONSTRAINT [TP__Promotion_Enabled] DEFAULT ((0)) NOT NULL,
    [DaysEnabled]                     INT            NULL,
    [PromotionOfferTypeId]            INT            NULL,
    [PromotionOfferValue]             FLOAT (53)     NULL,
    [PromotionThreshold]              FLOAT (53)     NULL,
    [TotalOffers]                     INT            CONSTRAINT [TP__Promotion__Total__67C95AEA] DEFAULT ((0)) NULL,
    [MisCode]                         VARCHAR (50)   NULL,
    [Message]                         VARCHAR (50)   NULL,
    [GroupItems]                      BIT            CONSTRAINT [TP__Promotion__Group__77CAB889] DEFAULT ((0)) NULL,
    [Personalized]                    BIT            CONSTRAINT [TP__Promotion__Perso__25918339] DEFAULT ((0)) NOT NULL,
    [PromotionItemFlagAnd]            BIT            CONSTRAINT [TP__Promotion__Promo__40106F4B] DEFAULT ((0)) NULL,
    [PromotionTypeId]                 INT            CONSTRAINT [TP__Promotion__Promo__194BA7E5] DEFAULT ((0)) NULL,
    [VoucherProfileId]                INT            NULL,
    [IncludePromotionItems]           BIT            CONSTRAINT [TP_Promotion_IncludePromotionItems] DEFAULT ((0)) NULL,
    [IsTemplate]                      BIT            NULL,
    [IsBonusRedemption]               BIT            NULL,
    [IsIndustryPromo]                 BIT            NULL,
    [MaxUsagePerMember]               INT            NULL,
    [OverrideBasePointRestriction]    BIT            NULL,
    [PromotionUsageLimit]             INT            NULL,
    [Quantity]                        INT            NULL,
    [PromotionCategoryId]             INT            NULL,
    [QualifyingProductQuantity]       FLOAT (53)     NULL,
    [EmailTemplateId]                 INT            NULL,
    [SmsTemplateId]                   INT            NULL,
    [PushTemplateId]                  INT            NULL,
    [MaxPromoApplicationOnSameBasket] INT            NULL,
    [PromoApplicationMaxValue]        INT            NULL,
    [MaxUsagePerBasket]               INT            NULL,
    [CriteriaId]                      INT            NULL,
    [Cumulation]                      INT            NULL,
    [Reward]                          VARCHAR (150)  NULL,
    [ActivityTypeId]                  INT            NULL,
    [ActivityReference]               VARCHAR (300)  NULL,
    [ActivityCategoryId]              INT            NULL,
    [ActivityCategoryTypeId]          INT            NULL,
    [ImageName]                       VARCHAR (100)  NULL,
    [ImageUrl]                        VARCHAR (1000) NULL,
    [ActivityConfiguration]           VARCHAR (MAX)  NULL,
    [PromotionHitLimitTypeId]         INT            NULL,
    [TimeZoneId]                      INT            NULL,
    [Config]                          VARCHAR (MAX)  NULL,
    [StampCardMultiplier]             FLOAT (53)     NULL,
    [ParentPromotionId]               INT            NULL,
    [IsCombinationOffer]              BIT            NULL,
    CONSTRAINT [PKY__Promotion] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [PK_Promotion_Time] CHECK ([StartTime] IS NULL AND [EndTime] IS NULL OR [StartTime] IS NOT NULL AND [EndTime] IS NOT NULL),
    CONSTRAINT [PK_PromotionTypeId] CHECK ([PromotionTypeId]=(0) OR [PromotionTypeId]=(1) OR [PromotionTypeId]=(2)),
    CONSTRAINT [FK_ActivityCategoryId] FOREIGN KEY ([ActivityCategoryId]) REFERENCES [dbo].[ActivityCategory] ([Id]),
    CONSTRAINT [FK_ActivityCategoryTypeId] FOREIGN KEY ([ActivityCategoryTypeId]) REFERENCES [dbo].[ActivityCategoryType] ([Id]),
    CONSTRAINT [FK_Promotion__promotionHitLimitTypeId] FOREIGN KEY ([PromotionHitLimitTypeId]) REFERENCES [dbo].[PromotionHitLimitType] ([Id]),
    CONSTRAINT [FK_Promotion_PromotionCategory] FOREIGN KEY ([PromotionCategoryId]) REFERENCES [dbo].[PromotionCategory] ([Id]),
    CONSTRAINT [FK_Promotion_VoucherProfileId] FOREIGN KEY ([VoucherProfileId]) REFERENCES [dbo].[VoucherDeviceProfileTemplate] ([Id]),
    CONSTRAINT [PK__Promotion__Site] FOREIGN KEY ([SiteId]) REFERENCES [dbo].[Site] ([SiteId]),
    CONSTRAINT [PK_Promotion_PromotionOfferType] FOREIGN KEY ([PromotionOfferTypeId]) REFERENCES [dbo].[PromotionOfferType] ([Id])
);


GO
ALTER TABLE [dbo].[Promotion] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);

