CREATE TABLE [dbo].[Ticket] (
    [TicketId]               INT           IDENTITY (1, 1) NOT NULL,
    [Version]                INT           CONSTRAINT [DF_Ticket_Version] DEFAULT ((0)) NOT NULL,
    [UserId]                 INT           NULL,
    [TicketIdentificationNo] VARCHAR (50)  NULL,
    [TicketTopicId]          INT           NULL,
    [TicketStatusId]         INT           NULL,
    [TicketPriorityId]       INT           NULL,
    [Subject]                VARCHAR (50)  NULL,
    [Description]            VARCHAR (MAX) NULL,
    [CreatedDate]            DATETIME      NULL,
    [UpdatedDate]            DATETIME      NULL,
    [SiteId]                 INT           NULL,
    [TypeOfContact]          INT           NULL,
    [DateOfContact]          DATETIME      NULL,
    [CardNo]                 VARCHAR (30)  NULL,
    [ContactTime]            VARCHAR (10)  NULL,
    [CreatedBy]              INT           NULL,
    [AssignedTo]             INT           NULL,
    [ClientId]               INT           NULL,
    CONSTRAINT [PK_Ticket1] PRIMARY KEY CLUSTERED ([TicketId] ASC) WITH (FILLFACTOR = 100, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_Ticket_AssignedTo] FOREIGN KEY ([AssignedTo]) REFERENCES [dbo].[User] ([UserId]),
    CONSTRAINT [FK_Ticket_ClientId] FOREIGN KEY ([ClientId]) REFERENCES [dbo].[Client] ([ClientId]),
    CONSTRAINT [FK_Ticket_CreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[User] ([UserId]),
    CONSTRAINT [FK_Ticket_SiteId] FOREIGN KEY ([SiteId]) REFERENCES [dbo].[Site] ([SiteId]),
    CONSTRAINT [FK_Ticket_TicketPriorityId] FOREIGN KEY ([TicketPriorityId]) REFERENCES [dbo].[TicketPriority] ([TicketPriorityId]),
    CONSTRAINT [FK_Ticket_TicketStatusId] FOREIGN KEY ([TicketStatusId]) REFERENCES [dbo].[TicketStatus] ([TicketStatusId]),
    CONSTRAINT [FK_Ticket_TicketTopicId] FOREIGN KEY ([TicketTopicId]) REFERENCES [dbo].[TicketTopic] ([TicketTopicId]),
    CONSTRAINT [FK_Ticket_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([UserId])
);

