CREATE TABLE [dbo].[VoucherDeviceProfileTemplate] (
    [Id]                   INT             NOT NULL,
    [ClassicalVoucher]     BIT             CONSTRAINT [DF_VoucherDeviceProfile_ClassicalVoucher] DEFAULT ((0)) NOT NULL,
    [SpendRequired]        DECIMAL (18, 2) NULL,
    [UseWithOthers]        BIT             NULL,
    [StartTime]            TIME (7)        NULL,
    [EndTime]              TIME (7)        NULL,
    [UseSameType]          BIT             NULL,
    [UseSameSubType]       BIT             NULL,
    [DaysEnabled]          INT             NULL,
    [MisCode]              VARCHAR (25)    NULL,
    [VoucherSubTypeId]     INT             NOT NULL,
    [OfferValue]           DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [PromotionType]        INT             NULL,
    [LogicalAnd]           BIT             NULL,
    [IncludePromotionItem] BIT             NULL,
    [VoucherHtml]          VARCHAR (MAX)   NULL,
    [ImageId]              INT             NULL,
    [BarcodeX]             INT             NULL,
    [BarcodeY]             INT             NULL,
    [BarcodeWidth]         INT             NULL,
    [BarcodeHeight]        INT             NULL,
    [BarcodeType]          VARCHAR (50)    NULL,
    [MaximumUsage]         INT             NULL,
    [VoucherReward]        VARCHAR (100)   NULL,
    [EnterCode]            BIT             NULL,
    [IsSingleLine]         BIT             NULL,
    [CheapestOrDearest]    VARCHAR (25)    NULL,
    [IsStampCard]          BIT             NULL,
    [DisplayInEcomm]       BIT             NULL,
    [DisplayInTill]        BIT             NULL,
    CONSTRAINT [PK_VoucherDeviceProfile] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_DeviceProfileTemplate_MarketingVoucherDeviceProfile] FOREIGN KEY ([Id]) REFERENCES [dbo].[DeviceProfileTemplate] ([Id]),
    CONSTRAINT [FK_VoucherDeviceProfileTemplate_VoucherDeviceProfileTemplate] FOREIGN KEY ([Id]) REFERENCES [dbo].[VoucherDeviceProfileTemplate] ([Id]),
    CONSTRAINT [FK_VoucherSubType_VoucherDeviceProfileTemplate] FOREIGN KEY ([VoucherSubTypeId]) REFERENCES [dbo].[VoucherSubType] ([VoucherSubTypeId])
);

